// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7I4zxZ86e4B9ZiewcjWx6zkLciFXEOg4',
    appId: '1:369846859068:web:9b87b10026fab699601a39',
    messagingSenderId: '369846859068',
    projectId: 'easy-reading-cb9bf',
    authDomain: 'easy-reading-cb9bf.firebaseapp.com',
    storageBucket: 'easy-reading-cb9bf.firebasestorage.app',
    measurementId: 'G-LZWX92GS9K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAebezTuHsVnKFEJaXGcDOZeYCoRhUKLMc',
    appId: '1:369846859068:android:7112de787cc40103601a39',
    messagingSenderId: '369846859068',
    projectId: 'easy-reading-cb9bf',
    storageBucket: 'easy-reading-cb9bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmaXDvwgOorQPK6OM-iKz43vKpdiQWbpw',
    appId: '1:369846859068:ios:3c9fd36d410d3dbc601a39',
    messagingSenderId: '369846859068',
    projectId: 'easy-reading-cb9bf',
    storageBucket: 'easy-reading-cb9bf.firebasestorage.app',
    iosBundleId: 'com.example.easyreadingRebuild',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmaXDvwgOorQPK6OM-iKz43vKpdiQWbpw',
    appId: '1:369846859068:ios:3c9fd36d410d3dbc601a39',
    messagingSenderId: '369846859068',
    projectId: 'easy-reading-cb9bf',
    storageBucket: 'easy-reading-cb9bf.firebasestorage.app',
    iosBundleId: 'com.example.easyreadingRebuild',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7I4zxZ86e4B9ZiewcjWx6zkLciFXEOg4',
    appId: '1:369846859068:web:3f7ab612ebe0abcb601a39',
    messagingSenderId: '369846859068',
    projectId: 'easy-reading-cb9bf',
    authDomain: 'easy-reading-cb9bf.firebaseapp.com',
    storageBucket: 'easy-reading-cb9bf.firebasestorage.app',
    measurementId: 'G-MBE3V2VGFR',
  );
}
